name: ppa

on:
  workflow_dispatch:

jobs:
  ppa:
    uses: ./.github/ci-helpers/.github/workflows/ppa-deb.yml
    with:
      working_directory: "."
      prebuild_command: "./scripts/generate_man.sh"
      build_command: "./scripts/build.sh"
